### ISSUE TITLE
OS error when trying to play multiplayer

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/Chess-Engine#13]
Sometimes, I get a python OS error when I try to play multiplayer. This usually happens when I close the main window before I close the python IDLE shell.

**Comment by TheLizzard** [comment]
Another time the error appears is when I play multiplayer, switch to PvP and back to multiplayer.

**Comment by TheLizzard** [comment]
While I tried fixing the error I got these errors (They are 2 different errors occurring simultaneously):
```
Exception in Tkinter callbackException in thread 
Thread-2Traceback (most recent call last):
:
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      File "/home/thelizzard/Desktop/Projects/Project/main.py", line 145, in menu
    self.start_game(event[1])
self.run()
  File "/home/thelizzard/Desktop/Projects/Project/main.py", line 222, in start_game
    self.board.add_user_as_player(True)
  File "/usr/lib/python3.8/threading.py", line 870, in run
      File "/home/thelizzard/Desktop/Projects/Project/board.py", line 202, in add_user_as_player
    self.kill_player(colour)
self._target(*self._args, **self._kwargs)
  File "/home/thelizzard/Desktop/Projects/Project/board.py", line 260, in kill_player
    self.players[not colour].destroy()
  File "/home/thelizzard/Desktop/Projects/Project/Networking/connector.py", line 111, in wait_for_connection
      File "/home/thelizzard/Desktop/Projects/Project/Players/multiplayer.py", line 48, in destroy
    self.connector.kill()
self.their_sock, self.their_address = self.our_sock.accept()
  File "/home/thelizzard/Desktop/Projects/Project/Networking/connector.py", line 129, in kill
    self.recver.stop()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    AttributeError: 'Connector' object has no attribute 'recver'
fd, addr = self._accept()
OSError: [Errno 22] Invalid argument
```

**Comment by TheLizzard** [comment]
Now getting this error:
```
Exception in thread Call from:Thread-2 : Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in Tkinter callback    
self.run()Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
    self._target(*self._args, **self._kwargs)  File "/home/thelizzard/Desktop/Projects/Project/main.py", line 145, in menu
    self.start_game(event[1])

  File "/home/thelizzard/Desktop/Projects/Project/Networking/connector.py", line 104, in wait_for_connection
  File "/home/thelizzard/Desktop/Projects/Project/main.py", line 237, in start_game
    self.board.start_multiplayer()
    self.their_sock, self.their_address = self.our_sock.accept()  File "/home/thelizzard/Desktop/Projects/Project/board.py", line 240, in start_multiplayer
    self.kill_player(not colour)

  File "/usr/lib/python3.8/socket.py", line 292, in accept
  File "/home/thelizzard/Desktop/Projects/Project/board.py", line 260, in kill_player
    self.players[not colour].destroy()
    fd, addr = self._accept()  File "/home/thelizzard/Desktop/Projects/Project/Players/multiplayer.py", line 52, in destroy
    self.connector.kill()

OSError  File "/home/thelizzard/Desktop/Projects/Project/Networking/connector.py", line 113, in kill
    raise
: [Errno 22] Invalid argumentRuntimeError: No active exception to reraise
```
This is when I force an error when the connection is destroyed twice.
