### ISSUE TITLE
Windows: socket not working

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/Chess-Engine#16]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "main.py", line 146, in menu
    self.start_game(event[1])
  File "main.py", line 269, in start_game
    self.board.start_multiplayer()
  File "C:\Users\Aleks\Downloads\Daniel\board.py", line 257, in start_multiplayer
    player = Multiplayer(self.board, self.master, colour, self.pieces,
  File "C:\Users\Aleks\Downloads\Daniel\Players\multiplayer.py", line 30, in __init__
    self.build_connection(ip, self.colour)
  File "C:\Users\Aleks\Downloads\Daniel\Players\multiplayer.py", line 67, in build_connection
    self.connector = Connector(ip=ip, port=65360, server=colour)
  File "C:\Users\Aleks\Downloads\Daniel\Networking\connector.py", line 75, in __init__
    self.our_sock.connect((ip, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by TheLizzard** [comment]
This issue might not come from Windows but be a logical error. I need to test it some more.
