### ISSUE TITLE
Windows: An error while the program is asking for IP address

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/Chess-Engine#17]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "main.py", line 146, in menu
    self.start_game(event[1])
  File "main.py", line 269, in start_game
    self.board.start_multiplayer()
  File "C:\Users\Aleks\Downloads\Daniel\board.py", line 257, in start_multiplayer
    player = Multiplayer(self.board, self.master, colour, self.pieces,
  File "C:\Users\Aleks\Downloads\Daniel\Players\multiplayer.py", line 27, in __init__
    ip = window.wait()
  File "C:\Users\Aleks\Downloads\Daniel\widgets.py", line 292, in wait
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1420, in mainloop
    self.tk.mainloop(n)
  File "C:\Users\Aleks\Downloads\Daniel\widgets.py", line 234, in _proxy
    return self.tk.call(cmd)
_tkinter.TclError: invalid command name ".!customtext_orig"
invalid command name ".!customtext_orig"
    while executing
".!customtext_orig see insert"
    invoked from within
"$w see insert"
    (procedure "tk::TextInsert" line 16)
    invoked from within
"tk::TextInsert .!customtext \n"
    (command bound to event)

**Comment by TheLizzard** [comment]
A temporary fix is adding a `try-except` block.
