### ISSUE TITLE
An error when trying input IP address for multiplayer

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/Chess-Engine#18]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "main.py", line 146, in menu
    self.start_game(event[1])
  File "main.py", line 269, in start_game
    self.board.start_multiplayer()
  File "C:\Users\TheLizzard\board.py", line 257, in start_multiplayer
    player = Multiplayer(self.board, self.master, colour, self.pieces,
  File "C:\Users\TheLizzard\Players\multiplayer.py", line 27, in __init__
    ip = window.wait()
  File "C:\Users\TheLizzard\widgets.py", line 292, in wait
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1420, in mainloop
    self.tk.mainloop(n)
  File "C:\Users\TheLizzard\widgets.py", line 234, in _proxy
    return self.tk.call(cmd)
_tkinter.TclError: invalid command name ".!customtext_orig"
invalid command name ".!customtext_orig"
    while executing
".!customtext_orig see insert"
    invoked from within
"$w see insert"
    (procedure "tk::TextInsert" line 16)
    invoked from within
"tk::TextInsert .!customtext \n"
    (command bound to event)
```

**Comment by TheLizzard** [comment]
Got the same error on Ubuntu so it isn't a Windows error
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/thelizzard/Desktop/Projects/Project (copy)/main.py", line 146, in menu
    self.start_game(event[1])
  File "/home/thelizzard/Desktop/Projects/Project (copy)/main.py", line 269, in start_game
    self.board.start_multiplayer()
  File "/home/thelizzard/Desktop/Projects/Project (copy)/board.py", line 257, in start_multiplayer
    player = Multiplayer(self.board, self.master, colour, self.pieces,
  File "/home/thelizzard/Desktop/Projects/Project (copy)/Players/multiplayer.py", line 29, in __init__
    ip = window.wait()
  File "/home/thelizzard/Desktop/Projects/Project (copy)/widgets.py", line 292, in wait
    self.root.mainloop()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1420, in mainloop
    self.tk.mainloop(n)
  File "/home/thelizzard/Desktop/Projects/Project (copy)/widgets.py", line 234, in _proxy
    return self.tk.call(cmd)
_tkinter.TclError: invalid command name ".!customtext_orig"
```
This is the first time this error popped up on my Ubuntu.

**Comment by TheLizzard** [comment]
It only appears if the user presses the `Enter` key. It triggers an event that destroys the widget but then tries to manipulate it (causing the error).
