### ISSUE TITLE
Rare errors where position is None while creating an arrow

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/Chess-Engine#7]
This is the traceback of the errors:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/thelizzard/Desktop/Projects/Project/user.py", line 125, in mouse
    self.user_helper_making = self.create_arrow(start, end)
  File "/home/thelizzard/Desktop/Projects/Project/user.py", line 145, in create_arrow
    coords1 = position1.to_coords()
AttributeError: 'NoneType' object has no attribute 'to_coords'

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/thelizzard/Desktop/Projects/Project/user.py", line 101, in mouse
    _hash = hash(start+end)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Position'
```
The first error appeared 4 times for some reason. It is very hard to reproduce but in the 2 cases that I got this error, I was dragging a piece and creating an arrow at the same time.

**Comment by TheLizzard** [comment]
I suspect the first error comes from the tkinter event where event.type._name_ is Motion. That is why it appeared 4 times. The second error comes from releasing the a mouse button and the computer trying to store information about the arrow which was never created.

**Comment by TheLizzard** [comment]
I confirmed that the first error comes from the tkinter event where `"ButtonPress-3"` isn't registered by the program so `self.user_created_arrow_start` is still `None` from the constructor of the class `User`.

I found a way to reliably reproduce this error:
1. Click with the right mouse button
2. Click with the left mouse button as fast as possible
3. Drag the piece
4. Let go of the left mouse button
5. Move the mouse around and the first error will appear
6. Let go with the right mouse button and the second error will appear

**Comment by TheLizzard** [comment]
The solution: break is `self.user_created_arrow_start` is `None` only works if the user hasn't drawn any arrows. If the user was drawn arrows on the screen then `self.user_created_arrow_start` is a `Position` object causing unexpected behaviours.

**Comment by TheLizzard** [comment]
A better solution would be to detect when both mouse buttons are down and disable arrow drawing.
